### ISSUE TITLE
Dokumentujte kod

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG002-bilijar#3]
(logiku kolizije i ostalo)

**Comment by krcma96** [comment]
Dodao sam komentare za sve sto sam mislio da je bitno i da nije ocigledno. Moj predlog je da idete redom kroz funkcije on_timer i on_draw i tako pratite tok izvrsavanja posto sam tako dodavao komentare. Dodao sam i sliku kako izgleda racunanje mog odbijanja. Javite ako treba za nesto konkretnije dokumentacija
